-- CreateTable
CREATE TABLE "Stats" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "date" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "teman" INTEGER NOT NULL DEFAULT 0,
    "kegiatan" INTEGER NOT NULL DEFAULT 0,
    "relawan" INTEGER NOT NULL DEFAULT 0,
    "donasi" INTEGER NOT NULL DEFAULT 0,
    "donatur" INTEGER NOT NULL DEFAULT 0,
    "pengguna" INTEGER NOT NULL DEFAULT 0
);
